### ISSUE TITLE
About the camera

### ISSUE THREAD

**Issue by ozzy69** [TomE8/drones#20]
Hello Tom, i use the project: https://hackaday.io/project/19680-controlling-a-jjrc-h37-elfie-quad-from-a-pc and i adaptide the code in my drone, however the camera is not working, How did you find the correct address of the camera?

**Comment by TomE8** [comment]
Note that the drone has only 1 up address. What distinguish the camera from and the engine control is the protocol type (tcp or udp) and the port. 
This information can be leraend from the source code of the app (quit hard to do), you can see it in the project you sent and in my code in this repo.

**Comment by ozzy69** [comment]
For sure man, in my drone the tcp address of the camera is 172.168.10.1:8888 and the udp is 172.168.10.1:8080, in the udp anddres i found the hexadecimal string for the taking off, stop, turn on, etc and I got here:
![Screenshot_2020-07-20_13-46-56](https://user-images.githubusercontent.com/16249363/87963803-d419d280-caa8-11ea-93b7-2ecf7f4a4396.png)
I was try to do the same with the program pull video, but is not working, but the hexadecimal strings is change a long the time, i was try to take one hexadecimal for test, but is not working
![Screenshot_2020-07-20_13-50-36](https://user-images.githubusercontent.com/16249363/87964080-3377e280-caa9-11ea-8ea5-f940ce70cdce.png)
do you have a suggestion to me find the correct hexadecimal string

**Comment by ozzy69** [comment]
How do you found this hexadecimal string?
heartbeat=bytearray([0x0,0x1,0x2,0x3,0x4,0x5,0x6,0x7,0x8,0x9,0x28,0x28])
![Screenshot_2020-07-20_14-28-17](https://user-images.githubusercontent.com/16249363/87967551-83a57380-caae-11ea-8681-d6e6a00e824c.png)
