### ISSUE TITLE
I managed to adaptide your program in my drone but,...

### ISSUE THREAD

**Issue by rrodrigofranco** [TomE8/drones#21]
Hello Tom, how are you?
I managed to adapt the your code on my drone, but the video arrives very slowly, is that so? Isn't there any way to change some parameters or something for the video to arrive normally on my pc without delays? Like, make the video quality worse or something? If so, could you help me?
and the variable buffersize, where did you get that value 4096? In the code it says that you got it from the "config file", is that config file the wireshark sniffer? If so, where in the sniffer should I go to find it? 

My sniffer's vide is here: https://sites.google.com/site/negocindosica/09%20-%20Filmando%20depois%20de%20concetar.pcapng

**Comment by TomE8** [comment]
Hey,
There are 3 steps in displaying the sent image:
1. receive the bytes of the image
2. process the bytes according to the image format (YUV in my case)
3. displaying the image to the screen 

Step #1 is negligible in time and computing power.
Step #2 is more demanding in terms of time and computing power then the step #1.
Step #3 has the highest "price". 

I have 3 suggestion that might help reduce the latency:
1. Display only part of the images. For example: display every 5th image and ignore the rest (don't display them)
2. Don't process bytes in step #2. I haven't think if it is possible, thou it is an option
3. Change the program to work in parallel. That way your computer will process images not in pip line.

In my opinion option 3 is the best option, thou it is complex. Option 1 is the essayist and might solve some of your problems.

**Comment by ozzy69** [comment]
Thanks, I'll try to do it!

**Comment by ozzy69** [comment]
I have another problem, the stream is showing upside down, to solve this problem I used the function "cv2.flip (image, -1)", but I would like to know if there is any way to change the process of step 2 by example, in that "YUV" function, if so, could you tell me how?

**Comment by TomE8** [comment]
I don't know, I think your solution is fine, thou if you want to place the flip inside YUV function you will have to read more about it yourself. good luck!
